import os
import logging

from reapy import reascript_api as RPR

from reaper_mcp.connection import ensure_connected

logger = logging.getLogger("reaper_mcp.midi_device_tools")

# ---------------------------------------------------------------------------
# Device presets
# ---------------------------------------------------------------------------

# Akai MIDImix factory default MIDI map (all messages on MIDI channel 1 = idx 0)
# Per-channel layout (4 controls each): [knobA_cc, knobB_cc, knobC_cc, fader_cc]
# Channels 1-4 start at CC 16; channels 5-8 start at CC 33 (skips 32).
_AKAI_MIDIMIX = {
    "name": "Akai MIDImix",
    "num_channels": 8,
    "midi_channel": 0,          # 0-indexed (MIDI channel 1)
    "fader_ccs":   [19, 23, 27, 31, 36, 40, 44, 48],  # ch1-8 volume faders
    "master_fader_cc": 62,
    "knob_rows": [
        [16, 20, 24, 28, 33, 37, 41, 45],  # row 1 – Send A
        [17, 21, 25, 29, 34, 38, 42, 46],  # row 2 – Send B
        [18, 22, 26, 30, 35, 39, 43, 47],  # row 3 – Send C / Pan
    ],
    "mute_notes":    [1,  4,  7, 10, 13, 16, 19, 22],
    "rec_arm_notes": [3,  6,  9, 12, 15, 18, 21, 24],
    "bank_left_note":  25,
    "bank_right_note": 26,
}

DEVICE_PRESETS: dict[str, dict] = {
    "akai_midimix": _AKAI_MIDIMIX,
    "midimix":      _AKAI_MIDIMIX,  # alias
}

# ---------------------------------------------------------------------------
# Lua script template
# ---------------------------------------------------------------------------

_LUA_TEMPLATE = """\
-- REAPER MCP: MIDI Mixer Mapping
-- Device : {device_name}
-- Input  : #{midi_input_index}
-- Tracks : {track_offset} .. {track_end}
-- Generated by reaper-mcp – do not edit by hand.

local TARGET_DEV  = {midi_input_index}   -- -1 = any device
local MIDI_CH     = {midi_channel}        -- 0-15 or -1 for any channel
local TRACK_OFF   = {track_offset}
local MASTER_CC   = {master_fader_cc}     -- nil if unused

-- CC -> relative track index (0 = first mapped track)
local FADER_MAP = {fader_map}

-- CC -> relative track index for pan (knob row 3)
local PAN_MAP = {pan_map}

-- Note -> relative track index for mute toggle
local MUTE_MAP = {mute_map}

local EXT_SECTION = "reaper_mcp_midi_mixer"
local EXT_STOP    = "stop"

-- ---- helpers --------------------------------------------------------------

local function vol_from_cc(v)
    if v == 0 then return 0.0 end
    return v / 127.0   -- linear: CC 127 = 0 dB (1.0)
end

local function pan_from_cc(v)
    return (v - 64) / 64.0   -- CC 64 = centre (0.0)
end

local function get_track(rel_idx)
    return reaper.GetTrack(0, rel_idx + TRACK_OFF)
end

local function process(buf, devIdx)
    if TARGET_DEV >= 0 and devIdx ~= TARGET_DEV then return end
    local b1 = string.byte(buf, 1) or 0
    local b2 = string.byte(buf, 2) or 0
    local b3 = string.byte(buf, 3) or 0
    local status = b1 & 0xF0
    local chan   = b1 & 0x0F
    if MIDI_CH >= 0 and chan ~= MIDI_CH then return end

    if status == 0xB0 then                          -- CC
        local ri = FADER_MAP[b2]
        if ri ~= nil then
            local t = get_track(ri)
            if t then reaper.SetMediaTrackInfo_Value(t, "D_VOL", vol_from_cc(b3)) end
        end
        if MASTER_CC ~= nil and b2 == MASTER_CC then
            local mt = reaper.GetMasterTrack(0)
            reaper.SetMediaTrackInfo_Value(mt, "D_VOL", vol_from_cc(b3))
        end
        local pi = PAN_MAP[b2]
        if pi ~= nil then
            local t = get_track(pi)
            if t then reaper.SetMediaTrackInfo_Value(t, "D_PAN", pan_from_cc(b3)) end
        end

    elseif status == 0x90 and b3 > 0 then           -- Note On
        local mi = MUTE_MAP[b2]
        if mi ~= nil then
            local t = get_track(mi)
            if t then
                local m = reaper.GetMediaTrackInfo_Value(t, "B_MUTE")
                reaper.SetMediaTrackInfo_Value(t, "B_MUTE", m > 0.5 and 0 or 1)
            end
        end
    end
end

-- Initialise: skip all events already in the buffer so we only react to
-- events that arrive AFTER this script starts.
local _ok0, _b0, _last_ts = reaper.MIDI_GetRecentInputEvent(0)
_last_ts = _last_ts or 0

-- ---- main poll loop -------------------------------------------------------

local function poll()
    if reaper.GetExtState(EXT_SECTION, EXT_STOP) == "1" then
        reaper.DeleteExtState(EXT_SECTION, EXT_STOP, false)
        reaper.ShowConsoleMsg("[reaper-mcp] MIDI mixer mapping stopped\\n")
        return   -- exit defer loop
    end

    -- Walk from most-recent (idx=0) backwards; break when we reach
    -- events older than the last processed timestamp.
    local seen = {}
    for i = 0, 1000 do
        local ok, buf, ts, devIdx = reaper.MIDI_GetRecentInputEvent(i)
        if not ok or not buf or #buf == 0 then break end
        if ts <= _last_ts then break end
        local key = string.format("%d:%d", string.byte(buf,1) & 0xF0, string.byte(buf,2) or 0)
        if not seen[key] then    -- keep only the most-recent value per CC/note
            seen[key] = true
            process(buf, devIdx)
        end
    end

    -- Advance timestamp to most-recent event
    local ok0, _, ts0 = reaper.MIDI_GetRecentInputEvent(0)
    if ok0 and ts0 then _last_ts = ts0 end

    reaper.defer(poll)
end

reaper.atexit(function()
    reaper.ShowConsoleMsg("[reaper-mcp] MIDI mixer mapping exited\\n")
end)

reaper.ShowConsoleMsg("[reaper-mcp] MIDI mixer mapping started (input #" .. TARGET_DEV .. ")\\n")
poll()
"""


def _lua_table(mapping: dict[int, int]) -> str:
    """Convert {cc_or_note: rel_track_idx} to a Lua table literal."""
    if not mapping:
        return "{}"
    entries = ", ".join(f"[{k}] = {v}" for k, v in sorted(mapping.items()))
    return "{" + entries + "}"


def register_tools(mcp):

    @mcp.tool()
    def list_midi_inputs() -> dict:
        """List all MIDI input devices currently visible to REAPER."""
        try:
            ensure_connected()
            n = RPR.GetNumMIDIInputs()
            devices = []
            for i in range(n):
                _, _, name, _ = RPR.GetMIDIInputName(i, "", 512)
                devices.append({"index": i, "name": name})
            return {"success": True, "count": n, "devices": devices}
        except Exception as e:
            logger.error(f"list_midi_inputs failed: {e}")
            return {"success": False, "error": str(e)}

    @mcp.tool()
    def list_midi_device_presets() -> dict:
        """List the built-in MIDI device presets available for mixer mapping."""
        seen: set[str] = set()
        presets = []
        for k, v in DEVICE_PRESETS.items():
            if v["name"] not in seen:
                seen.add(v["name"])
                presets.append({
                    "preset_name": k,
                    "device_name": v["name"],
                    "num_channels": v["num_channels"],
                })
        return {"success": True, "presets": presets}

    @mcp.tool()
    def get_device_preset(preset_name: str) -> dict:
        """
        Return the full CC/note layout for a named device preset.
        Use list_midi_device_presets() to see available names.
        """
        key = preset_name.lower().replace(" ", "_")
        preset = DEVICE_PRESETS.get(key)
        if preset is None:
            return {"success": False, "error": f"Unknown preset '{preset_name}'. "
                    f"Available: {list(DEVICE_PRESETS.keys())}"}
        return {"success": True, "preset": preset}

    @mcp.tool()
    def apply_midi_mixer_mapping(
        midi_input_index: int,
        preset_name: str = "akai_midimix",
        track_offset: int = 0,
        num_tracks: int = 8,
        map_pan: bool = True,
        map_mute: bool = True,
    ) -> dict:
        """
        Map a physical MIDI control device to REAPER mixer channels.

        Writes a Lua ReaScript to REAPER's Scripts directory and starts it as a
        background action.  The script runs in a defer loop, translating incoming
        MIDI CC / Note messages into track volume, pan, and mute changes.

        midi_input_index : index from list_midi_inputs() – e.g. the Akai MIDImix.
        preset_name      : device layout preset (default "akai_midimix").
        track_offset     : first REAPER track index to control (0-based).
        num_tracks       : how many consecutive tracks to map (max = device channels).
        map_pan          : if True, knob row 3 controls track pan.
        map_mute         : if True, mute buttons toggle track mute.

        Call stop_midi_mixer_mapping() to stop the running script.
        """
        try:
            ensure_connected()
            key = preset_name.lower().replace(" ", "_")
            preset = DEVICE_PRESETS.get(key)
            if preset is None:
                return {"success": False, "error": f"Unknown preset '{preset_name}'"}

            n = min(num_tracks, preset["num_channels"], len(preset["fader_ccs"]))

            fader_map: dict[int, int] = {
                preset["fader_ccs"][i]: i for i in range(n)
            }
            pan_map: dict[int, int] = {}
            if map_pan and len(preset["knob_rows"]) >= 3:
                pan_row = preset["knob_rows"][2]  # row 3 = Send C / Pan
                pan_map = {pan_row[i]: i for i in range(min(n, len(pan_row)))}
            mute_map: dict[int, int] = {}
            if map_mute and preset.get("mute_notes"):
                mutes = preset["mute_notes"]
                mute_map = {mutes[i]: i for i in range(min(n, len(mutes)))}

            master_cc = preset.get("master_fader_cc", "nil")
            if master_cc is None:
                master_cc = "nil"

            # Use simple token replacement instead of .format() to avoid
            # conflicts between Python format syntax and Lua table braces.
            replacements = {
                "{device_name}":      preset["name"],
                "{midi_input_index}": str(midi_input_index),
                "{midi_channel}":     str(preset.get("midi_channel", 0)),
                "{track_offset}":     str(track_offset),
                "{track_end}":        str(track_offset + n - 1),
                "{master_fader_cc}":  str(master_cc),
                "{fader_map}":        _lua_table(fader_map),
                "{pan_map}":          _lua_table(pan_map),
                "{mute_map}":         _lua_table(mute_map),
            }
            script_body = _LUA_TEMPLATE
            for token, value in replacements.items():
                script_body = script_body.replace(token, value)

            resource_path = RPR.GetResourcePath()
            scripts_dir = os.path.join(resource_path, "Scripts", "reaper-mcp")
            os.makedirs(scripts_dir, exist_ok=True)
            script_path = os.path.join(scripts_dir, "midi_mixer_mapping.lua")

            with open(script_path, "w") as f:
                f.write(script_body)

            # Register and run the script
            action_id = RPR.AddRemoveReaScript(True, 0, script_path, True)
            if not action_id:
                return {"success": False, "error": "Failed to register ReaScript with REAPER"}

            RPR.Main_OnCommand(action_id, 0)

            return {
                "success": True,
                "message": (
                    f"MIDI mixer mapping started for '{preset['name']}' "
                    f"(input #{midi_input_index}), "
                    f"tracks {track_offset}–{track_offset + n - 1}."
                ),
                "script_path": script_path,
                "action_id": action_id,
                "num_tracks_mapped": n,
                "fader_ccs": list(fader_map.keys()),
                "pan_ccs": list(pan_map.keys()),
                "mute_notes": list(mute_map.keys()),
                "master_fader_cc": preset.get("master_fader_cc"),
            }
        except Exception as e:
            logger.error(f"apply_midi_mixer_mapping failed: {e}")
            return {"success": False, "error": str(e)}

    @mcp.tool()
    def stop_midi_mixer_mapping() -> dict:
        """
        Stop the MIDI mixer mapping script started by apply_midi_mixer_mapping().
        Signals the running Lua script to exit on its next polling cycle (~30 ms).
        """
        try:
            ensure_connected()
            RPR.SetExtState("reaper_mcp_midi_mixer", "stop", "1", False)
            return {"success": True, "message": "Stop signal sent to MIDI mixer mapping script."}
        except Exception as e:
            logger.error(f"stop_midi_mixer_mapping failed: {e}")
            return {"success": False, "error": str(e)}
